SELECT 'step1' AS step;
SELECT id_usuario, id_perfil, id_unidade, id_local INTO @v_id_usuario, @v_id_perfil, @v_id_unidade, @v_id_local FROM sessao_usuario WHERE id_sessao_usuario = 201 LIMIT 1;
SELECT @v_id_usuario AS id_usuario, @v_id_perfil AS id_perfil, @v_id_unidade AS id_unidade, @v_id_local AS id_local;
SELECT 'step2' AS step;
SELECT id_painel INTO @v_id_painel FROM painel WHERE tipo = 'TOTEM' AND id_unidade = @v_id_unidade LIMIT 1;
SELECT @v_id_painel AS id_painel;
SELECT 'step3' AS step;
SELECT tipo_atendimento INTO @v_tipo_senha FROM totem_senha_opcao WHERE id_opcao = 1 AND id_painel = @v_id_painel AND ativo = 1 LIMIT 1;
SELECT @v_tipo_senha AS tipo_senha;
SELECT 'step4' AS step;
SELECT prefixo, codigo INTO @v_prefixo, @v_codigo_visual FROM totem_senha_opcao WHERE id_painel = @v_id_painel AND tipo_atendimento = @v_tipo_senha AND ativo = 1 LIMIT 1;
SELECT @v_prefixo AS prefixo, @v_codigo_visual AS codigo_visual;
SELECT 'step5' AS step;
SELECT id_senha_status, codigo INTO @v_id_status, @v_codigo_status FROM senha_status WHERE codigo = 'EMITIDA' AND ativo = 1 LIMIT 1;
SELECT @v_id_status AS id_status, @v_codigo_status AS codigo_status;
SELECT 'step6' AS step;
SET @v_numero_senha = CONCAT(@v_prefixo, LPAD(IFNULL((SELECT IFNULL(MAX(ultimo_numero), 0) + 1 FROM senha_sequencia WHERE id_unidade = @v_id_unidade AND prefixo = @v_prefixo AND DATE(data_ref) = CURDATE()), 1), 3, '0'));
SELECT @v_numero_senha AS numero_senha;
SELECT 'done' AS step;
