import {
  Stethoscope,
  Pill,
  Boxes,
  Warehouse,
  LayoutDashboard,
  Newspaper,
  GraduationCap,
  FileText,
  LifeBuoy,
} from "lucide-react";
import type { PortalModule } from "../types/portal";

/**
 * Catálogo de módulos do Portal Corporativo.
 *
 * A arquitetura é genérica: os módulos abaixo são exemplos de aplicações que a
 * plataforma pode hospedar. Cada cliente habilita os módulos que desejar e o
 * portal exibe apenas aqueles que o usuário tem permissão de acessar.
 */
export const portalModules: PortalModule[] = [
  {
    id: "atendimento",
    name: "Atendimento",
    description: "Operação de atendimento e fluxo de senhas.",
    icon: Stethoscope,
    type: "operational",
    enabled: true,
    permission: "mod.atendimento",
    route: "/operacional/atendimento",
    accent: "blue",
  },
  {
    id: "farmacia",
    name: "Farmácia",
    description: "Dispensação e controle de medicamentos.",
    icon: Pill,
    type: "operational",
    enabled: true,
    permission: "mod.farmacia",
    route: "/operacional/farmacia",
    accent: "green",
  },
  {
    id: "estoque",
    name: "Estoque",
    description: "Entradas, saídas e saldo de itens.",
    icon: Boxes,
    type: "operational",
    enabled: true,
    permission: "mod.estoque",
    route: "/operacional/estoque",
    accent: "amber",
  },
  {
    id: "almoxarifado",
    name: "Almoxarifado",
    description: "Gestão de materiais e suprimentos internos.",
    icon: Warehouse,
    type: "operational",
    enabled: true,
    permission: "mod.almoxarifado",
    route: "/operacional",
    accent: "cyan",
  },
  {
    id: "gestao",
    name: "Gestão",
    description: "Indicadores e dashboards de gestão.",
    icon: LayoutDashboard,
    type: "standalone",
    enabled: true,
    permission: "mod.gestao",
    route: "/portal/gestao",
    accent: "indigo",
  },
  {
    id: "intranet",
    name: "Intranet",
    description: "Comunicação interna e rede social corporativa.",
    icon: Newspaper,
    type: "standalone",
    enabled: true,
    permission: "mod.intranet",
    route: "/portal/intranet",
    accent: "violet",
  },
  {
    id: "treinamentos",
    name: "Treinamentos",
    description: "Cursos, trilhas e certificações.",
    icon: GraduationCap,
    type: "standalone",
    enabled: true,
    permission: "mod.treinamentos",
    route: "/portal/treinamentos",
    accent: "rose",
  },
  {
    id: "documentos",
    name: "Documentos",
    description: "Gestão documental e versionamento.",
    icon: FileText,
    type: "standalone",
    enabled: true,
    permission: "mod.documentos",
    route: "/portal/documentos",
    accent: "slate",
  },
  {
    id: "chamados",
    name: "Chamados",
    description: "Central de chamados e suporte interno.",
    icon: LifeBuoy,
    type: "standalone",
    enabled: true,
    permission: "mod.chamados",
    route: "/portal/chamados",
    accent: "blue",
  },
];
