-- GENERATED BY KILO ENGINE
-- STATUS: PROPOSED
-- REQUIRE APPROVAL
--
-- =========================================================
-- ORIGEM:   MD-REGISTRY-001 / MAP-REGISTRY-001 / BR-REGISTRY-001
--          (Ciclo 2.1 — Registry Canônico, etapa 1/5)
-- OBJETIVO: EXTEND de `permissao` para Capability Registry
--           (REUSE/ADAPT do Banco Vivo — NÃO cria nova tabela)
-- DUMP:     ✅ encontrado (permissao, Dump20260618.sql L11733)
-- AÇÃO:    ALTER TABLE permissao  (classificação EXTEND/MERGE)
-- CONTRATO: Capacidade resolvida por Capability Resolver
-- PIPELINE: Capability → Authorization → Execution (LEI 25·26)
-- INVARIANTES: BR-CAP-001..008
-- =========================================================

ALTER TABLE `permissao`
  -- Tipo lógico da capability (filtro por consumidor, ex: IA)
  ADD COLUMN `tipo_capability` ENUM(
        'OPERACAO','CONSULTA','EVENTO','INTEGRACAO','SISTEMA','IA'
  ) NOT NULL DEFAULT 'OPERACAO'
  COMMENT 'Tipo da capability (BR-CAP-003)',

  -- Código canônico estável usado pelo Resolver / AI Runtime
  ADD COLUMN `capacidade_codigo` VARCHAR(120) NULL
  COMMENT 'Código canônico <dominio>.<acao> (BR-CAP-002)',

  -- ADAPT de contrato (registry já existe no dump)
  ADD COLUMN `id_contrato` BIGINT NULL
  COMMENT '→ contrato / saas_contrato (ADAPT, etapa posterior cabeia FK)',

  -- ↓↓↓ colunas downstream entram NULL; cabeadas nas etapas 2 e 3 ↓↓↓
  -- Cardinalidade (1:1 embrionário) EM REVISÃO (BR-CAP-010):
  -- pode evoluir para N:N via capability_runtime / capability_tool.
  ADD COLUMN `id_runtime` BIGINT NULL
  COMMENT '→ runtime_registry (etapa 2); N:N futuro via junção',

  ADD COLUMN `id_tool` BIGINT NULL
  COMMENT '→ tool_registry (etapa 3); N:N futuro via junção',

  ADD COLUMN `payload_contrato` JSON NULL
  COMMENT 'Contrato de entrada/saída da capability',

  -- Índices de resolução
  ADD KEY `idx_perm_tipo` (`tipo_capability`),
  ADD KEY `idx_perm_capacidade` (`capacidade_codigo`);

-- Backfill defensivo: capabilities operacionais já existentes
-- recebem código canônico derivado de codigo (sem quebrar unicidade).
UPDATE `permissao`
   SET `capacidade_codigo` = LOWER(CONCAT(`dominio`, '.', `codigo`))
 WHERE `capacidade_codigo` IS NULL
   AND `nome_procedure` IS NOT NULL;
