-- GENERATED BY KILO ENGINE
-- STATUS: PROPOSED
-- REQUIRE APPROVAL
--
-- Template de proposta de migration.
-- Substitua os metadados e o corpo conforme MD/MAP de origem.
-- Nunca altere o dump original (database/dump/).

-- =========================================================
-- ORIGEM:   MD-xxx / MAP-xxx / FRONT-xxx
-- OBJETIVO: <descrever a entidade/SP ausente no dump>
-- DUMP:     ❌ não encontrado
-- AÇÃO:    PROPOSTA DE CRIAÇÃO
-- =========================================================

/*
CREATE TABLE dbo.<entidade> (
    id            UNIQUEIDENTIFIER NOT NULL,
    tenant_id     UNIQUEIDENTIFIER NOT NULL,
    codigo        VARCHAR(64)      NOT NULL,
    nome          VARCHAR(128)     NOT NULL,
    status        VARCHAR(16)      NOT NULL DEFAULT 'ATIVO',
    criado_em     DATETIME         NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_<entidade> PRIMARY KEY (id)
);
*/
